update cicd workflow

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -1,15 +1,12 @@
-# 워크플로의 이름 지정
 name: CI/CD
 
-# 워크플로가 시작될 조건 지정
 on:
   push:
     branches: [ master ]
 
 jobs:
   build:
-    runs-on: ubuntu-latest # 실행 환경 지정
-    #실행 스탭 지정
+    runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
       - uses: actions/setup-java@v3
@@ -22,7 +19,7 @@ jobs:
           mkdir -p src/main/resources
           echo "${{ secrets.APPLICATION_YML }}" > src/main/resources/application.yml
 
-      - name: Grant excute permission for gradlew
+      - name: Grant execute permission for gradlew
         run: chmod +x gradlew
 
       - name: Build with Gradle
@@ -36,7 +33,7 @@ jobs:
           utcOffset: "+09:00"
 
       - name: Set artifact
-        run: echo "artifact=$(ls ./build/libs)" >> @GITHUB_ENV
+        run: echo "artifact=$(ls ./build/libs)" >> $GITHUB_ENV
 
       - name: Deploy to Server
         uses: appleboy/ssh-action@master
@@ -46,5 +43,5 @@ jobs:
           key: ${{ secrets.SERVER_SSH_KEY }}
           script: |
             echo "${{ secrets.APPLICATION_YML }}" > ~/app/application.yml
-            cp ${{ github.workspace }}/build/libs/*.jar ~/app/app.jar
-            sudo systemctl restart smartfarm.service
+            find ${{ github.workspace }}/build/libs -name '*.jar' -type f -exec cp {} ~/app/app.jar \;
+            sudo -n systemctl restart smartfarm.service || echo "Failed to restart service. May require manual intervention."
